### ISSUE TITLE
Firebase API key should be hidden.

### ISSUE THREAD

**Issue by iammarkps** [dtinth/screen-master#1]
**Type : Discussion**
In src/firebase.ts, firebase API key is exposed. It should be hidden in my opinion, shouldn't it?

**Comment by dtinth** [comment]
For a Firebase web app to function, an API key is needed on the client. Therefore the API key here is considered "public". Security is achieved through server-side rules.

See: https://stackoverflow.com/a/37484053/559913

**Comment by iammarkps** [comment]
So your intention is to let anyone use your firebase project?

**Comment by dtinth** [comment]
Yes, I plan to not require people to create their own Firebase project just to use this tool. What people can do with the Firebase project through the API key is pretty limited:

- Sign in with GitHub (it's the only enabled with option)
- Use the realtime database according to the rules

The API key doesn't give administrative access.

This project runs on a free plan, so the worst thing that can happen is that the app hits the quota and becomes unusable. At that point users have to setup their own project.

**Comment by iammarkps** [comment]
Can you write a documentation for setting up a new firebase project?
If you don't have time, I can help with writing it. But now I don't know hows to config it in firebase.
